name: Web Uygulama 1
on: 
    push:
        branches:
            - main

jobs:
    build: 
        runs-on: ubuntu-latest

        steps: 
          - name: Repodan kodu cek
            uses: actions/checkout@v2
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1
    
          - name: Login to Docker Hub
            uses: docker/login-action@v1
            with:
              username: ${{ secrets.USERNAME }}
              password: ${{ secrets.PASSWORD }}

          - name: Build and Push Docker Image
            run: |
                cd webuygulama
                docker buildx create --use
                docker build -t hacer01/cicdeneme:latest .
                docker push hacer01/cicdeneme:latest
            env:
                DOCKER_CLI_EXPERIMENTAL: enabled